package com.se2.communication.dto;

public enum MessageType {
    JOIN_LOBBY,
    JOINED_LOBBY,
    NEW_PLAYER_JOINED,
    PLAYER_LEFT_LOBBY,
    LEAVE_LOBBY,
    CHEATING_TILT_RIGHT,
    CHEATING_TILT_LEFT,
    CHEATING_LIGHT,
    START_GAME,
    UPDATEBOARD,
    WORMHOLE_MOVE
}
